spring:
  datasource:
    url: jdbc:mysql://cricguru-db.cpiius8geitg.ap-south-1.rds.amazonaws.com:3306/cricguru_db?useSSL=false
    username: cricguru
    password: CricGuru#19
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  level:
    org:
      springframework:
        web: INFO
      apache:
        jasper: INFO
